---
- hosts: all
  become: true
  tasks:
  - name: Installing Environment Packages
    yum:
      name: "{{item}}"
      state: present
    with_items:
      - httpd
      - vsftpd
      - ipa-server
      - libselinux-python
      - bind*
      - ipa-server-dns
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding IP address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.5 ipa.example.com ipa
      create: yes
  - name: Rebuilding host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Configuring IPA server
    command: ipa-server-install --setup-dns --allow-zone-overlap -a 'password' --hostname=ipa.example.com -r EXAMPLE.COM -p 'password' -n example.com -U --forwarder 8.8.8.8
  - name: Enabling services
    service: name={{item}} enabled=true
    with_items:
      - httpd
      - vsftpd
      - firewalld
  - name: Starting services
    service: name={{item}} state=started
    with_items:
      - vsftpd
      - firewalld
  - name: Allowing Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Rebooting machine
    reboot: