---
- hosts: ipa
  strategy: free
  gather_facts: False
  tasks:
  - name: Fixing hosts file
    lineinfile:
      dest: /etc/hosts
      regexp: '^127\.0\.0\.1'
      state: absent
  - name: Adding localhost IPV4 address to host file
    lineinfile:
      path: /etc/hosts
      line: 127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
      create: yes
  - name: Adding localhost IPV6 address to host file
    lineinfile:
      path: /etc/hosts
      line: ::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
      create: yes
  - name: Adding IPA address to hosts file
    lineinfile:
      path: /etc/hosts
      line: 192.168.55.30 ipa.example.com ipa
      create: yes
## Add your clients IP address below
#  - name: Adding system1 address to hosts file
#    lineinfile:
#      path: /etc/hosts
#      line: 192.168.55.6 system1.example.com system1
#      create: yes
  - name: Installing Environment Packages
    command: yum install -y ipa-server ipa-server-dns vsftpd
  - name: Enabling services
    service: name={{item}} enabled=true
    with_items:
      - httpd
      - vsftpd
      - firewalld
      - ntpd
  - name: Starting Firewalld
    service: name=firewalld state=started
  - name: Enabling Firewall Services
    command: firewall-cmd --permanent --add-service=http --add-service=https --add-service=ntp --add-service=dns --add-service=kerberos --add-service=ldap --add-service=ldaps --add-service=ftp
  - name: Reloading Firewall
    command: firewall-cmd --reload
  - name: Configuring network
    shell: nmcli con mod "System eth1" ipv4.addresses 192.168.55.30/24 ipv4.gateway 192.168.55.1 ipv4.dns 8.8.8.8 ipv4.dns-search example.com ipv4.method manual
  - name: Reloaded Network. Configuring IPA server...(Est. Time - 7 minutes)
    shell: nmcli con up "System eth1"  
  - name: Finishing IPA server Configuration
    command: sudo ipa-server-install --setup-dns --allow-zone-overlap --auto-reverse -a 'password' --hostname=ipa.example.com -r EXAMPLE.COM -p 'password' -n example.com -U --forwarder 8.8.8.8